### ISSUE TITLE
Move API_Root_Url to .env file

### ISSUE THREAD

**Issue by wdunn001** [safe-refuge/safe-refuge-bot#6]
Migrate Api_Root_Url to .env and a placeholder in .example file under config rather than hardcoded.

location:
https://github.com/safe-refuge/safe-refuge-bot/blob/master/src/safe_refuge_calls/api_url_service.py

**Comment by kommade** [comment]
is using sys/os ok?

**Comment by wdunn001** [comment]
you just throw it in the .env file and read it from there the same way it reads the telegram key

**Comment by kommade** [comment]
> you just throw it in the .env file and read it from there the same way it reads the telegram key

that uses telegram's ConversationHandler
